import {
  Accessibility,
  BadgeCheck,
  BookOpenCheck,
  Brain,
  Briefcase,
  Building2,
  CalendarCheck,
  ClipboardCheck,
  Coins,
  Ear,
  FileCheck2,
  FileSignature,
  FileText,
  Globe,
  HandHeart,
  Heart,
  House,
  Lightbulb,
  MapPin,
  Megaphone,
  MessageCircle,
  Moon,
  Quote,
  Rocket,
  Search,
  Share2,
  ShieldCheck,
  Sparkles,
  Star,
  Users,
  UserRound,
  type LucideIcon,
} from "lucide-react";

export const SERVICE_ICONS: Record<string, LucideIcon> = {
  // /care Cluster A
  "personal-care": HandHeart,
  "home-care": House,
  "live-in-care": Moon,
  "respite-care": Heart,
  companionship: MessageCircle,
  "specialist-care": ShieldCheck,
  // /care Cluster B
  "older-people": UserRound,
  dementia: Brain,
  "physical-disability": Accessibility,
  "learning-disability": Sparkles,
  "mental-health": Heart,
  "sensory-impairment": Ear,
  // /care Cluster C
  "areas-we-cover": MapPin,
  "fees-funding": Coins,
  "cqc-rating": BadgeCheck,
  testimonials: Quote,
  refer: ClipboardCheck,
  careers: Users,
  // /agency Cluster A
  "cqc-registration": BadgeCheck,
  "policies-procedures": FileCheck2,
  "statement-of-purpose": FileText,
  "business-plans": Briefcase,
  "interview-readiness": BookOpenCheck,
  "inspection-readiness": ClipboardCheck,
  // /agency Cluster B
  "tender-writing": FileSignature,
  frameworks: Building2,
  "tender-pricing": Coins,
  opportunities: Search,
  // /agency Cluster C
  "digital-services": Globe,
  "branding-kits": Megaphone,
  "social-presence": Share2,
  "digital-audit": Search,
  // /agency Cluster D
  staffing: Users,
  "hr-documents": FileText,
  // /agency Cluster E
  consulting: Lightbulb,
  coaching: MessageCircle,
  "launch-kit": Rocket,
  "case-studies": Star,
  "book-a-call": CalendarCheck,
};
